version: '1.0'

services:

  postgres:
    image: postgres:16
    container_name: aspmanager-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  aspmanager-service-discovery:
    image: aspmanager-service-discovery:latest
    container_name: aspmanager-service-discovery
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", ${EUREKA_ACTUATOR_URL}]
      interval: 10s

  aspmanager-gateway:
    image: aspmanager-gateway:latest
    container_name: aspmanager-gateway
    ports:
      - "8080:8080"
    depends_on:
      aspmanager-service-discovery:
        condition: service_healthy
    environment:
      EUREKA_URL: ${EUREKA_URL}

  aspmanager-auth-service:
    image: aspmanager-auth-service:latest
    ports:
      - "8081:8081"
    depends_on:
      aspmanager-service-discovery:
        condition: service_healthy
    environment:
      EUREKA_URL: ${EUREKA_URL}
      JWT_SECRET: ${JWT_SECRET}

  aspmanager-usuario-service:
    image: aspmanager-usuario-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - aspmanager-service-discovery
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}db_usuario
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EUREKA_URL: ${EUREKA_URL}

  aspmanager-escola-service:
    image: aspmanager-escola-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - aspmanager-service-discovery
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}db_escola
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EUREKA_URL: ${EUREKA_URL}

  aspmanager-espaco-service:
    image: aspmanager-espaco-service:latest
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - aspmanager-service-discovery
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}db_espaco
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EUREKA_URL: ${EUREKA_URL}

  aspmanager-software-service:
    image: aspmanager-software-service:latest
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - aspmanager-service-discovery
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}db_software
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EUREKA_URL: ${EUREKA_URL}

volumes:
  postgres_data:







