server:
  port: 8080

spring:
  application:
    name: aspmanager-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: aspmanager-auth-service
              uri: lb://ASPMANAGER-AUTH-SERVICE
              predicates:
                - Path=/api/auth/**
              filters:
                - name: JwtAuthFilter
                  args:
                    excludePaths: /auth/login,/auth/validate

            - id: aspmanager-usuario-service
              uri: lb://ASPMANAGER-USUARIO-SERVICE
              predicates:
                - Path=/api/v1/usuarios/**
              filters:
                - JwtAuthFilter

            - id: aspmanager-escola-service
              uri: lb://ASPMANAGER-ESCOLA-SERVICE
              predicates:
                - Path=/api/v1/instituicoes/**,/api/v1/escolas/**,/api/v1/disciplinas/**
              filters:
                - JwtAuthFilter

            - id: aspmanager-espaco-service
              uri: lb://ASPMANAGER-ESPACO-SERVICE
              predicates:
                - Path=/api/v1/espacos/**
              filters:
                - JwtAuthFilter

            - id: aspmanager-software-service
              uri: lb://ASPMANAGER-SOFTWARE-SERVICE
              predicates:
                - Path=/api/v1/softwares/**
              filters:
                - JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}